name = "Hugo Future Imperfect Slim"
license = "Creative Commons Attribution 3.0"
licenselink = "https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/LICENSE.md"
description = "A multilingual blogging template."
homepage = "https://github.com/pacollins/hugo-future-imperfect-slim"
tags = ["HTML5", "CSS3", "Mobile", "Responsive", "Blog", "Portfolio",
        "Disqus", "Staticman", "Highlight.js", "Fancybox", "Font Awesome",
        "Academicons", "jQuery", "Netlify", "Open Graph". "Multilingual",
        "Google Analytics", "Light", "Company", "Contact Form", "Gallery",
        "Business"]
features = ["Highlight.js", "Normalize.css", "Font Awesome", "Fancybox",
            "Academicons", "Google Analytics", "Disqus", "Staticman",
            "Twitter Cards", "Open Graph", "Google News", "jQuery", "Netlify"]
min_version = 0.57

[author]
  name = "Patrick Collins"
  homepage = "https://pacollins.com"

# If porting an existing theme
[original]
  name = "Future Imperfect"
  homepage = "https://html5up.net/future-imperfect"
  repo = "https://html5up.net/future-imperfect"
